### ISSUE TITLE
問題修正 26件以上の問題で発生する

### ISSUE THREAD

**Issue by kazuma11121125** [HSS-Project/HSS-bot#21]
`Jun 01 22:56:58 munesky python3[718]: [2024-06-01 22:56:58] [ERROR   ] discord.ui.view: Ignoring exception in view <MemorizationControlView timeout=180.0 children=7> for item <Button style=<ButtonStyle.danger: 4> url=None disabled=False label='問題編集' emoji=None row=None>
Jun 01 22:56:58 munesky python3[718]: Traceback (most recent call last):
Jun 01 22:56:58 munesky python3[718]:   File "/home/munesky/HSS-bot/.venv/lib/python3.12/site-packages/discord/ui/view.py", line 427, in _scheduled_task
Jun 01 22:56:58 munesky python3[718]:     await item.callback(interaction)
Jun 01 22:56:58 munesky python3[718]:   File "/home/munesky/HSS-bot/cogs/memorization_maker_add_discord.py", line 678, in edit
Jun 01 22:56:58 munesky python3[718]:     self.view.add_item(MemorizationEditSelect(lists, self.title,self.base_count))
Jun 01 22:56:58 munesky python3[718]:                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 01 22:56:58 munesky python3[718]:   File "/home/munesky/HSS-bot/cogs/memorization_maker_add_discord.py", line 452, in __init__
Jun 01 22:56:58 munesky python3[718]:     super().add_option(option)
Jun 01 22:56:58 munesky python3[718]: TypeError: Select.add_option() takes 1 positional argument but 2 were given`

**Comment by kazuma11121125** [comment]
@yaakiyu 普通にわからん

**Comment by yaakiyu** [comment]
```py
[2024-06-01 22:56:58] [ERROR   ] discord.ui.view: Ignoring exception in view <MemorizationControlView timeout=180.0 children=7> for item <Button style=<ButtonStyle.danger: 4> url=None disabled=False label='問題編集' emoji=None row=None>
Traceback (most recent call last):
  File "/home/munesky/HSS-bot/.venv/lib/python3.12/site-packages/discord/ui/view.py", line 427, in _scheduled_task
    await item.callback(interaction)
  File "/home/munesky/HSS-bot/cogs/memorization_maker_add_discord.py", line 678, in edit
    self.view.add_item(MemorizationEditSelect(lists, self.title,self.base_count))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/munesky/HSS-bot/cogs/memorization_maker_add_discord.py", line 452, in __init__
    super().add_option(option)
TypeError: Select.add_option() takes 1 positional argument but 2 were given
```

**Comment by yaakiyu** [comment]
https://github.com/HSS-Project/HSS-bot/blob/main/cogs/memorization_maker_add_discord.py#L452
ここを`self.add_option(option)`にしてあげればよさそう

**Comment by kazuma11121125** [comment]
それでうまくいかないんですよね
