### ISSUE TITLE
memorizationのバグ。解答終わり

### ISSUE THREAD

**Issue by kazuma11121125** [HSS-Project/HSS-bot#23]
`
● hss-bot.service - HSS-bot
     Loaded: loaded (/etc/systemd/system/hss-bot.service; enabled; preset: enabled)
     Active: active (running) since Sun 2024-06-02 14:58:29 JST; 1 day 3h ago
   Main PID: 687 (python3)
      Tasks: 6 (limit: 3482)
     Memory: 64.6M (peak: 64.8M)
        CPU: 48.414s
     CGroup: /system.slice/hss-bot.service
             ├─ 687 /home/munesky/HSS-bot/.venv/bin/python3 /home/munesky/HSS-bot/main.py
             └─6812 systemctl status hss-bot.service
Jun 03 18:52:27 munesky python3[687]:   File "/home/munesky/HSS-bot/cogs/memorization_maker_view_discord.py", line 193, in callback
Jun 03 18:52:27 munesky python3[687]:     await memorizationPlayMain.main_start(interaction)
Jun 03 18:52:27 munesky python3[687]:   File "/home/munesky/HSS-bot/cogs/memorization_maker_view_discord.py", line 323, in main_start
Jun 03 18:52:27 munesky python3[687]:     await interaction.response.send_message(embed=embed,ephemeral=True)
Jun 03 18:52:27 munesky python3[687]:   File "/home/munesky/HSS-bot/.venv/lib/python3.12/site-packages/discord/interactions.py", line 801, in send_message
Jun 03 18:52:27 munesky python3[687]:     await adapter.create_interaction_response(
Jun 03 18:52:27 munesky python3[687]:   File "/home/munesky/HSS-bot/.venv/lib/python3.12/site-packages/discord/webhook/async_.py", line 221, in request
Jun 03 18:52:27 munesky python3[687]:     raise HTTPException(response, data)
Jun 03 18:52:27 munesky python3[687]: discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
Jun 03 18:52:27 munesky python3[687]: In data.embeds.0.fields: Must be 25 or fewer in length.
`

**Comment by kazuma11121125** [comment]
mode 0 1で問題ある模様

**Comment by yaakiyu** [comment]
単純に項目数多すぎるだけでは？`In data.embeds.0.fields: Must be 25 or fewer in length.`って言われてるし

**Comment by kazuma11121125** [comment]
あ、モード関係ないな
（単語テスト間違えまくった結果のバグです）
対応しないとな
分別送信とか、、？

**Comment by kazuma11121125** [comment]
解決させた
